channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - nb_conda
  
  - python=3.9
  - openjdk
  - pandas
  - pyarrow
  - pip
  - pyspark
  - python-duckdb
  - paramiko

  - pip:
    - dagster>=0.14.12
    - dagster-docker>=0.14.12
    - dagster-ssh>=0.14.12
    - dagster-pandas>=0.14.12
    - dagster-postgres>=0.14.12
    - dagster-dbt>=0.14.12
    - dagster-pyspark>=0.14.12
    - dagit>=0.14.12
    - dbt-core
    - dbt-postgres
    - dbt-duckdb
    - polars
    - jupyterlab