channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - nb_conda
  
  - python=3.9
  - pandas
  - pyarrow
  - pip
  - pyspark
  - python-duckdb
  - paramiko

  - pip:
    - dagster
    - dagster-ssh
    - dagster-pandas
    - dagster-postgres
    - dagster-dbt
    - dagster-pyspark
    - dbt-core
    - dbt-postgres
    - dbt-duckdb
    - dagit
    - polars
    - jupyterlab